pub const DAY_IN_LEDGERS: u32 = 17280;
pub const CHAIN_ID: u32 = 7;
pub const CHAIN_PRECISION: u32 = 7;
pub const INSTANCE_EXTEND_TTL_AMOUNT: u32 = 7 * DAY_IN_LEDGERS;
pub const INSTANCE_LIFETIME_THRESHOLD: u32 = INSTANCE_EXTEND_TTL_AMOUNT - DAY_IN_LEDGERS;
