[package]
name = "bridge_storage"
version = "0.1.0"
edition = "2021"

[dependencies]
soroban-sdk = { workspace = true }
soroban-env-common = { workspace = true }
shared = { workspace = true }
proc_macros = { workspace = true }
